### ISSUE TITLE
Getting rid of the OpenMP dependency

### ISSUE THREAD

**Issue by burgholzer** [cda-tum/ddsim#31]
Currently DDSIM uses OpenMP to parallelize the hybrid Schrodinger-Feynman simulation approach. There are two places where OpenMP is used:
 - In https://github.com/iic-jku/ddsim/blob/36661b7ec71a6c6f0cbf7abfb67fbba3f192926c/src/HybridSchrodingerFeynmanSimulator.cpp#L134 where a stack of tasks is concurrently accessed by a set number of threads in a `parallel` region.
 - In https://github.com/iic-jku/ddsim/blob/36661b7ec71a6c6f0cbf7abfb67fbba3f192926c/src/HybridSchrodingerFeynmanSimulator.cpp#L219 where a simple parallel for loop is used to calculate independent results

The DDSIM project provides Python wheels that essentially bundle all needed libraries into a portable wheel. OpenMP is known to cause all kinds of troubles/incompatibilities (see, e.g., pytorch/pytorch/issues/44282 or dmlc/xgboost/issues/1715).
As a consequence, it would be great to get rid of this dependency altogether.

With the near-term integration of #30, the taskflow (https://github.com/taskflow/taskflow) library is available as an external dependency of DDSIM. It is certainly possible to reformulate the above use cases in taskflow.

Any contributions are welcome!

**Comment by hillmich** [comment]
#30 is merged. Next step: Get rid of the OpenMP dependency :)
